[project]
name = "complete-learnlens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.2.1",
    "pyodbc>=5.2.0",
    "requests>=2.32.4",
    "streamlit>=1.45.1",
]
